### ISSUE TITLE
ImportError: No module named thirdparty.multipart

### ISSUE THREAD

**Issue by n1n741** [rebe11ion/rebel-framework#1]
{REBEL}➤[web/cmsscan]~# run

Traceback (most recent call last):
  File "cmsmap.py", line 5, in <module>
    from thirdparty.multipart import multipartpost
ImportError: No module named thirdparty.multipart

how i can fix this ? 

thank you

**Comment by rebe11ion** [comment]
Thanks for submitting your issue n1n741, you can try it now it should work.
